# Generated by Django 3.2.5 on 2021-08-04 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210804_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='_network_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='_network_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
